"""Registered error codes for the CruxNexus platform."""

# Authentication
INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
TOKEN_INVALID = "TOKEN_INVALID"
TENANT_ACCESS_DENIED = "TENANT_ACCESS_DENIED"
MEMBERSHIP_REQUIRED = "MEMBERSHIP_REQUIRED"

# Merchant / storefront
MERCHANT_REQUIRED = "MERCHANT_REQUIRED"
MERCHANT_STOREFRONT_CAPACITY_EXCEEDED = "MERCHANT_STOREFRONT_CAPACITY_EXCEEDED"
STOREFRONT_CONFLICT = "STOREFRONT_CONFLICT"
TENANT_NOT_FOUND = "TENANT_NOT_FOUND"
TENANT_NOT_READY = "TENANT_NOT_READY"
TENANT_MISMATCH = "TENANT_MISMATCH"

# Capacity / entitlements
CAPACITY_EXCEEDED = "CAPACITY_EXCEEDED"
PLAN_UPGRADE_REQUIRED = "PLAN_UPGRADE_REQUIRED"

# Onboarding
ONBOARDING_VALIDATION_ERROR = "ONBOARDING_VALIDATION_ERROR"
ONBOARDING_CONFLICT = "ONBOARDING_CONFLICT"
ONBOARDING_FAILED = "ONBOARDING_FAILED"

# Authorization
FORBIDDEN = "FORBIDDEN"
PLATFORM_ADMIN_REQUIRED = "PLATFORM_ADMIN_REQUIRED"

# Generic
VALIDATION_ERROR = "VALIDATION_ERROR"
INTERNAL_ERROR = "INTERNAL_ERROR"
NOT_FOUND = "NOT_FOUND"
